YouTube Watcher/config/routes.rb
Rails.application.routes.draw do
  resources :executed_searches
  resources :users
  resources :youtube_searches
  resources :videos
  resources :audits
  resources :alerts
  resources :user_signups
  resources :user_sessions

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  get 'static_pages/about', as: 'about'
  get 'static_pages/help', as: 'help'

  root 'dashboard#index'
end

YouTube Watcher/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

YouTube Watcher/app/helpers/dashboard_helper.rb
module DashboardHelper
end

YouTube Watcher/app/views/dashboard/_alerts.html.erb
<div class="nice-box sm-col-3">
  <div class="header row">
    Your Alerts
    <%= link_to 'View', alerts_path, class: 'btn btn-default pull-right' %>
  </div>
  <div class="contents row">
      <table class="table">
        <thead>
          <tr>
            <th>Last Triggered</th>
            <th>Status</th>
          </tr>
      </table>
  </div>
</div>

YouTube Watcher/app/views/dashboard/_searches.html.erb
<div class="nice-box">
  <div class="row">
    <div class="header">Your Searches
      <%= link_to 'New', new_youtube_search_path, class: 'btn btn-default pull-right' %>
    </div>
  </div>
  <div class="row contents">
      <table class="table">
        <% current_user.youtube_searches.most_recent(10).each do |search| %>
          <tr>
            <td><%= alert_glyph(search) %></td>
            <td><%= link_to search.name, edit_youtube_search_path(search) %></td>
          </tr>
        <% end %>
      </table>
    </div>
</div>

YouTube Watcher/app/views/dashboard/_system_activity.html.erb
<div class="nice-box">
  <div class="header">System Activity</div>
  <div class="contents">
      <table class="table">
        <% current_user.executed_searches.most_recent(10).each do |search| %>
          <tr>
            <td><%= search_type(search) %></td>
            <td><%= link_to search.name, executed_search_path(search) %></td>
            <td><%= time_ago_in_words(search.finished_at) unless search.finished_at.blank? %></td>
          </tr>
        <% end %>
      </table>
    </div>
</div>

YouTube Watcher/app/views/dashboard/index.html.erb
<table class="table">
  <tr class="row">
    <td><%= render 'alerts' %></td>
    <td><%= render 'searches' %></td>
    <td><%= render 'system_activity' %></td>
  </tr>
</table>