YouTube Watcher/config/routes.rb
Rails.application.routes.draw do
  resources :executed_searches
  resources :users
  resources :youtube_searches
  resources :videos
  resources :audits
  resources :alerts
  resources :user_signups
  resources :user_sessions

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  get 'static_pages/about', as: 'about'
  get 'static_pages/help', as: 'help'

  root 'dashboard#index'
end

YouTube Watcher/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ccc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <div class="app-header row">
        <div class="col-sm-12">
          <div class="row">
            <div class='col-sm-3'>
              <%= image_tag 'icon.png', height: '100px', class: 'icon' %>
            </div>
            <div class='col-sm-9'>
              <div class="row">
                <div class="name pull-right">YouTube Watcher</div>
              </div>
              <div class="row">
                <div class="subname pull-right">A CS4540 Production</div>
              </div>
              <% if logged_in? %>
                <div class="row top-links-row">
                  <ul class='top-links pull-right'>
                    <li><%= link_to 'Dashboard', root_path %></li>
                    <li>&bull;</li>
                    <li><%= link_to 'Profile', edit_user_path(current_user) %></li>
                    <li>&bull;</li>
                    <li><%= link_to 'About', about_path %></li>
                    <li>&bull;</li>
                    <li><%= link_to 'Help', help_path %></li>
                    <li>&bull;</li>
                    <li><%= link_to 'Logout', logout_path, method: :delete %></li>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="app-body row">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>