YouTube Watcher/config/routes.rb
Rails.application.routes.draw do
  resources :executed_searches
  resources :users
  resources :youtube_searches
  resources :videos
  resources :audits
  resources :alerts
  resources :user_signups
  resources :user_sessions

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  get 'static_pages/about', as: 'about'
  get 'static_pages/help', as: 'help'

  root 'dashboard#index'
end

YouTube Watcher/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :ensure_logged_in, except: :destroy

  def new
  end

  def create
    user = User.find_by(email: user_session_params[:email].downcase)
    if user && user.authenticate(user_session_params[:password])
      log_in(user)
      redirect_to :root
    else
      flash.now[:danger] = 'Invalid credentials'
      render :new
    end
  end

  def destroy
    log_out
    flash[:notice] = 'You have been logged out.'
    redirect_to new_user_session_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end
end

YouTube Watcher/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

YouTube Watcher/app/views/user_sessions/new.html.erb
<div class='content'>
  <%= form_for(:user_session, url: login_path, html: { class: 'form-horizontal' } ) do |form| %>
    <div class="form-group">
      <div class='col-sm-3'>
        <%= form.label :email, class: 'control-label' %>
      </div>
      <div class='col-sm-5'>
        <%= form.text_field :email, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class='col-sm-3'>
        <%= form.label :password, class: 'control-label' %>
      </div>
      <div class='col-sm-5'>
        <%= form.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class='col-sm-3'></div>
      <div class='col-sm-5'>
        <%= form.submit :login, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
  <p>New user?  <%= link_to 'Sign up now!', new_user_path, class: 'btn btn-default' %></p>
</div>